services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: buzon_db
      POSTGRES_USER: buzon_user
      POSTGRES_PASSWORD: buzon_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_buzon:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data_buzon:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data_buzon:
  redis_data_buzon:

## docker compose up -d
